plugins:
  - jekyll-relative-links
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-midnight

title: [LoolzRules's website]
description: [Welcome to my website]

permalink: /:categories/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "assets/**/*"
    values:
      sitemap: false
  -
    scope:
      path: "_posts/*"
    values:
      layout: post

loolzrules:
  channel: loolzrules_channel
