theme: jekyll-theme-midnight

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

exclude:
  - .idea
  - .gitignore

title: [LoolzRules's website]
description: [Welcome to my website]

collections:
  channel:
    output: true

defaults:
  -
    scope:
      path: "assets/**/*"
    values:
      sitemap: false
  -
    scope:
      path: "_channel/*.md"
    values:
      permalink: /channel/:year/:month/:day/:title/
      layout: post

loolzrules:
  channel: loolzrules_channel
